export enum FeatureEnum {
    WIFI = 'wifi',
    PARKING = 'parking',
    POOL = 'pool',
    GYM = 'gym',
    AIR_CONDITIONING = 'air_conditioning',
    PET_FRIENDLY = 'pet_friendly',
    RESTAURANT = 'restaurant',
    SPA = 'spa',
    BAR = 'bar',
    BEACH_ACCESS = 'beach_access',
    LAUNDRY_SERVICE = 'laundry_service',
    ROOM_SERVICE = 'room_service',
    FREE_BREAKFAST = 'free_breakfast',
    BUSINESS_CENTER = 'business_center',
    FAMILY_FRIENDLY = 'family_friendly',
    SMOKE_FREE = 'smoke_free',
    AIRPORT_SHUTTLE = 'airport_shuttle',
    PARKING_GARAGE = 'parking_garage',
    HOT_TUB = 'hot_tub',
    ELEVATOR = 'elevator',
    FREE_WIFI = 'free_wifi',
    H24_RECEPTION = '24h_reception',
  }
  